name: Build Sites
on:
  push:
    branches:
      - main
jobs:
  dispatch:
    strategy:
      matrix:
        repo: ['dineshb-ucsd/dineshb.github.io', 'ucsdwcsng/ucsdwcsng.github.io']
        pat: ['${{ secrets.DINESHB_PAT }}', '${{ secrets.WCSNG_PAT }}']
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ matrix.pat }}
          repository: ${{ matrix.repo }}
          event-type: dispatch-build
          client-payload: '{}'
